### ISSUE TITLE
Error in playlist validation

### ISSUE THREAD

**Issue by L0SER8228** [DevAndromeda/youtube-sr#30]
https://youtube.com/playlist?list=RDCLAK5uy_lj-zBExVYl7YN_NxXboDIh4A-wKGfgzNY&playnext=1
This above url is not validated, though the following is fine
https://youtube.com/playlist?list=RDCLAK5uy_lj-zBExVYl7YN_NxXboDIh4A-wKGfgzNY

**Comment by DevAndromeda** [comment]
try validating `ID` instead of `URL`

**Comment by DevAndromeda** [comment]
stale, re-open if needed
