### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by DMNight6** [DevAndromeda/youtube-sr#42]
It works in the previous version 4.1.11. After updating to 4.1.12, it returns

```
Compiled with problems:

ERROR in ./node_modules/youtube-sr/dist/mod.mjs 1:0-58

Module not found: Error: Can't resolve 'module' in 'C:\Users\arnok\OneDrive\Desktop\Bots item\React-JS\youtubedownload\node_modules\youtube-sr\dist'
```

**Comment by DevAndromeda** [comment]
Are you using esm?

**Comment by DevAndromeda** [comment]
Module is imported here https://github.com/DevAndromeda/youtube-sr/blob/0935cf008c787af84cb2be7331c4971f7d28c881/scripts/postbuild.js#L5

**Comment by DMNight6** [comment]
> Are you using esm?

yes

**Comment by DevAndromeda** [comment]
es modules import seems to work fine on the latest version, is it still happening? @DMNight6 

```js
/* test.mjs */
import { YouTube } from "youtube-sr";

console.log((await YouTube.search("levitating"))[0].title);
// node test.mjs -> "Dua Lipa - Levitating Featuring DaBaby (Official Music Video)"
```

**Comment by DMNight6** [comment]
Fixed by using backend

**Comment by DMNight6** [comment]
now its invalid url (youtube itself)

**Comment by DevAndromeda** [comment]
invalid url?

**Comment by DMNight6** [comment]
> invalid url?

yep
when I tried to getVideo using url

**Comment by DevAndromeda** [comment]
could you provide the url? @DMNight6

**Comment by DevAndromeda** [comment]
stale, re-open if needed
