### ISSUE TITLE
Suggestion - Get video quality

### ISSUE THREAD

**Issue by lyall-pc** [DevAndromeda/youtube-sr#45]
It would be nice if you could get the max quality of the specified video from youtube-sr

**Comment by DevAndromeda** [comment]
information about video's streaming data is available since [v4.3.0](https://github.com/DevAndromeda/youtube-sr/releases/tag/v4.3.0)

You can get info about video quality and stuff with this. You can access it with `video.formats`/`video.adaptiveFormats`/`video.streamingData`
