### ISSUE TITLE
Discord bot can't get YouTube Playlist Thumbnails

### ISSUE THREAD

**Issue by GPBR815** [DevAndromeda/youtube-sr#47]
When i try to load a youtube playlist into my bot, it gives me the following error: "given: Thumbnail { id: null, width: 0, height: 0, url: null }", while when i use other commands like load a single YouTube song, or even Spotify playlists, the thumbnails works fine, is there a way to fix it? Thanks in advance

**Comment by DevAndromeda** [comment]
https://github.com/DevAndromeda/youtube-sr/releases/tag/v4.3.2
